backend:
  name: git-gateway
  branch: main  # Branch to update (optional; defaults to master)
  media_folder: "public/assets/blog"
  public_folder: "/assets/blog"
collections:
name: 'blog'
label: 'Blog'
folder: 'src/blog'
create: true
slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}